sankaku_secrets:
  username: your_sankaku_username
  password: your_sankaku_password
  save_dir: C:/files_will_be_saved_here/
  base_url: https://chan.sankakucomplex.com/en/posts?tags=neptunia_%28series%29+rating%3AG
  first_page_num: 1
  last_page_num: 10
  login_url: https://chan.sankakucomplex.com/users/login
  compare_existing: True
